// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHuQuOZFzw6ZfDCfWWL_N2O4rOyBE0pBw',
    appId: '1:840665764219:web:afe9525b6b79e9e804edde',
    messagingSenderId: '840665764219',
    projectId: 'traitz-commerce',
    authDomain: 'traitz-commerce.firebaseapp.com',
    storageBucket: 'traitz-commerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSkVfJC1aI94_RL9soONROjakUnrizQo',
    appId: '1:840665764219:android:8d85fa32569968de04edde',
    messagingSenderId: '840665764219',
    projectId: 'traitz-commerce',
    storageBucket: 'traitz-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKC0Ck1QlfbxMSNDVXNcCzMp07yD7zI1A',
    appId: '1:840665764219:ios:5c37a7fc2974a1ab04edde',
    messagingSenderId: '840665764219',
    projectId: 'traitz-commerce',
    storageBucket: 'traitz-commerce.appspot.com',
    iosBundleId: 'com.example.traitzCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKC0Ck1QlfbxMSNDVXNcCzMp07yD7zI1A',
    appId: '1:840665764219:ios:5c37a7fc2974a1ab04edde',
    messagingSenderId: '840665764219',
    projectId: 'traitz-commerce',
    storageBucket: 'traitz-commerce.appspot.com',
    iosBundleId: 'com.example.traitzCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHuQuOZFzw6ZfDCfWWL_N2O4rOyBE0pBw',
    appId: '1:840665764219:web:b56ec03a52cc287204edde',
    messagingSenderId: '840665764219',
    projectId: 'traitz-commerce',
    authDomain: 'traitz-commerce.firebaseapp.com',
    storageBucket: 'traitz-commerce.appspot.com',
  );
}
